Switch to hibernate 6: - JDK 8 : not compatible anymore - JDK 11 : KO -> java.lang.NoClassDefFoundError: jakarta/xml/bind/JAXBException: jakarta.xml.bind.JAXBException